# Generated by Django 2.0.7 on 2018-07-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'Данные страницы обо мне', 'verbose_name_plural': 'Данные страницы обо мне'},
        ),
    ]
