# Generated by Django 2.0.7 on 2018-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180731_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='my_photo',
            field=models.ImageField(default=None, null=True, upload_to='media/media/uploads'),
        ),
    ]
